package apply

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/parmcoder/smt/internal/config"
)

func TestMobileApplyInvokesFlutterCLIInStagedOrder(t *testing.T) {
	logPath := installFakeASDF(t, false)
	parent := t.TempDir()
	destination := filepath.Join(parent, "workspace")
	cfg, err := config.LoadBytes(mobileBlueprintBytes(), filepath.Join(parent, "blueprint.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	service := Service{
		Config:        *cfg,
		Prerequisites: prerequisiteFunc(func(context.Context) error { return nil }),
		Beads:         initializerFunc(func(context.Context, string) error { return nil }),
	}
	if err := service.Apply(context.Background(), destination, mobileBlueprintBytes()); err != nil {
		t.Fatal(err)
	}

	cwd, args, toolVersions := readFakeASDFInvocation(t, logPath)
	if len(args) == 0 {
		t.Fatal("Flutter CLI was not invoked")
	}
	stagedMobile := args[len(args)-1]
	wantArgs := []string{
		"exec",
		"flutter",
		"--suppress-analytics",
		"create",
		"--empty",
		"--no-pub",
		"--platforms=android,ios",
		"--org=com.example.smt",
		"--project-name=smt_mobile",
		"--description=A provider-neutral SMT Flutter mobile starter.",
		stagedMobile,
	}
	if fmt.Sprint(args) != fmt.Sprint(wantArgs) {
		t.Fatalf("Flutter argv=%q, want %q", args, wantArgs)
	}
	if cwd != filepath.Dir(stagedMobile) {
		t.Fatalf("Flutter cwd=%q, want staged root %q", cwd, filepath.Dir(stagedMobile))
	}
	if stagedMobile == filepath.Join(destination, "mobile-app") {
		t.Fatalf("Flutter received published destination %q", stagedMobile)
	}
	if !strings.Contains(toolVersions, "flutter 3.44.9-stable") {
		t.Fatalf("Flutter ran before root .tool-versions was written: %q", toolVersions)
	}

	for _, relative := range []string{"android/cli-owned.txt", "ios/cli-owned.txt"} {
		if _, err := os.Stat(filepath.Join(destination, "mobile-app", relative)); err != nil {
			t.Fatalf("CLI-owned platform output %s missing: %v", relative, err)
		}
	}
	for _, relative := range []string{"android/gradlew", "ios/Runner.xcodeproj/project.pbxproj"} {
		if _, err := os.Stat(filepath.Join(destination, "mobile-app", relative)); !os.IsNotExist(err) {
			t.Fatalf("static platform fallback output %s exists: %v", relative, err)
		}
	}
}

func TestNonMobileApplyDoesNotInvokeFlutterCLI(t *testing.T) {
	logPath := installFakeASDF(t, false)
	parent := t.TempDir()
	destination := filepath.Join(parent, "workspace")
	cfg, err := config.LoadBytes(blueprintBytes(), filepath.Join(parent, "blueprint.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	service := Service{
		Config:        *cfg,
		Prerequisites: prerequisiteFunc(func(context.Context) error { return nil }),
		Beads:         initializerFunc(func(context.Context, string) error { return nil }),
	}
	if err := service.Apply(context.Background(), destination, blueprintBytes()); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(logPath); !os.IsNotExist(err) {
		t.Fatalf("non-Mobile Apply invoked asdf: %v", err)
	}
}

func TestFlutterCLIFailureLeavesNoPublishedWorkspaceAndGuidesAsdf(t *testing.T) {
	installFakeASDF(t, true)
	parent := t.TempDir()
	destination := filepath.Join(parent, "workspace")
	cfg, err := config.LoadBytes(mobileBlueprintBytes(), filepath.Join(parent, "blueprint.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	service := Service{
		Config:        *cfg,
		Prerequisites: prerequisiteFunc(func(context.Context) error { return nil }),
		Beads:         initializerFunc(func(context.Context, string) error { return nil }),
	}
	err = service.Apply(context.Background(), destination, mobileBlueprintBytes())
	if err == nil || !strings.Contains(err.Error(), "asdf install flutter 3.44.9-stable") || !strings.Contains(err.Error(), "asdf current flutter") {
		t.Fatalf("Apply() error=%v, want actionable asdf guidance", err)
	}
	if _, statErr := os.Lstat(destination); !os.IsNotExist(statErr) {
		t.Fatalf("published destination exists after Flutter failure: %v", statErr)
	}
	assertNoStage(t, parent)
}

func TestMobileApplyPreservesFlutterCLIOutput(t *testing.T) {
	installFakeASDF(t, false)
	parent := t.TempDir()
	destination := filepath.Join(parent, "workspace")
	cfg, err := config.LoadBytes(mobileBlueprintBytes(), filepath.Join(parent, "blueprint.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	service := Service{
		Config:        *cfg,
		Prerequisites: prerequisiteFunc(func(context.Context) error { return nil }),
		Beads:         initializerFunc(func(context.Context, string) error { return nil }),
	}
	if err := service.Apply(context.Background(), destination, mobileBlueprintBytes()); err != nil {
		t.Fatal(err)
	}
	child := filepath.Join(destination, "mobile-app")
	wantFiles := map[string]string{
		"pubspec.yaml":                   "name: smt_mobile\ndescription: Generated by fake Flutter CLI.\npublish_to: \"none\"\nversion: 0.1.0+1\n\nenvironment:\n  sdk: \">=3.12.0 <4.0.0\"\n  flutter: \">=3.44.9\"\n\ndependencies:\n  flutter:\n    sdk: flutter\n\ndev_dependencies:\n  flutter_lints: ^5.0.0\n  flutter_test:\n    sdk: flutter\n\nflutter:\n  uses-material-design: true\n",
		"pubspec.lock":                   "lock generated by Flutter CLI\n",
		"analysis_options.yaml":          "include: cli-analysis.yaml\n",
		"lib/main.dart":                  "created by Flutter CLI\n",
		"test/widget_test.dart":          "created by Flutter CLI\n",
		"integration_test/app_test.dart": "created by Flutter CLI\n",
		"android/cli-owned.txt":          "created by Flutter CLI\n",
		"ios/cli-owned.txt":              "created by Flutter CLI\n",
	}
	for relative, want := range wantFiles {
		got, err := os.ReadFile(filepath.Join(child, relative))
		if err != nil {
			t.Fatalf("CLI-owned output %s missing: %v", relative, err)
		}
		if string(got) != want {
			t.Fatalf("CLI-owned output %s=%q, want %q", relative, got, want)
		}
	}
}

func TestMobileApplyRemovesFlutterIDEFilesBeforePublish(t *testing.T) {
	installFakeASDF(t, false)
	parent := t.TempDir()
	destination := filepath.Join(parent, "workspace")
	cfg, err := config.LoadBytes(mobileBlueprintBytes(), filepath.Join(parent, "blueprint.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	service := Service{
		Config:        *cfg,
		Prerequisites: prerequisiteFunc(func(context.Context) error { return nil }),
		Beads:         initializerFunc(func(context.Context, string) error { return nil }),
	}
	if err := service.Apply(context.Background(), destination, mobileBlueprintBytes()); err != nil {
		t.Fatal(err)
	}
	child := filepath.Join(destination, "mobile-app")
	if _, err := os.Stat(filepath.Join(child, ".idea")); !os.IsNotExist(err) {
		t.Fatalf("Flutter IDE state survived publish: %v", err)
	}
	for _, relative := range []string{"pubspec.yaml", "pubspec.lock", "lib/main.dart", "android/cli-owned.txt", "ios/cli-owned.txt"} {
		if _, err := os.Stat(filepath.Join(child, relative)); err != nil {
			t.Fatalf("CLI output %s was removed with .idea: %v", relative, err)
		}
	}
}

func TestRealFlutterCreatePubGetAndAnalyzeWhenOptedIn(t *testing.T) {
	if os.Getenv("SMT_REAL_FLUTTER") != "1" {
		t.Skip("set SMT_REAL_FLUTTER=1 to run the local asdf/Flutter verification lane")
	}
	if _, err := exec.LookPath("asdf"); err != nil {
		t.Skipf("asdf unavailable: %v", err)
	}
	if output, err := exec.Command("asdf", "exec", "flutter", "--version").CombinedOutput(); err != nil {
		t.Skipf("selected Flutter unavailable through asdf: %v: %s", err, output)
	}
	parent := t.TempDir()
	destination := filepath.Join(parent, "workspace")
	cfg, err := config.LoadBytes(mobileBlueprintBytes(), filepath.Join(parent, "blueprint.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	service := Service{
		Config:        *cfg,
		Prerequisites: prerequisiteFunc(func(context.Context) error { return nil }),
		Beads:         initializerFunc(func(context.Context, string) error { return nil }),
	}
	if err := service.Apply(context.Background(), destination, mobileBlueprintBytes()); err != nil {
		t.Fatal(err)
	}
	child := filepath.Join(destination, "mobile-app")
	for _, args := range [][]string{{"exec", "flutter", "pub", "get"}, {"exec", "flutter", "analyze"}} {
		command := exec.CommandContext(context.Background(), "asdf", args...)
		command.Dir = child
		if output, err := command.CombinedOutput(); err != nil {
			t.Fatalf("asdf %v failed: %v: %s", args, err, output)
		}
	}
}

func installFakeASDF(t *testing.T, fail bool) string {
	t.Helper()
	directory := t.TempDir()
	logPath := filepath.Join(directory, "asdf.log")
	script := `#!/bin/sh
set -eu
log="$SMT_FAKE_ASDF_LOG"
printf 'cwd=%s\n' "$PWD" >> "$log"
if [ -f "$PWD/.tool-versions" ]; then
  printf 'tool-versions=%s\n' "$(tr '\n' '|' < "$PWD/.tool-versions")" >> "$log"
else
  printf 'tool-versions=<missing>\n' >> "$log"
fi
for arg in "$@"; do
  printf 'arg=%s\n' "$arg" >> "$log"
done
destination=""
for arg in "$@"; do destination="$arg"; done
if [ "${SMT_FAKE_ASDF_FAIL:-0}" = "1" ]; then
  mkdir -p "$destination/lib"
  printf 'partial\n' > "$destination/lib/partial.dart"
  exit 17
fi
mkdir -p "$destination/lib" "$destination/test" "$destination/integration_test" "$destination/android" "$destination/ios" "$destination/.idea/libraries" "$destination/.idea/runConfigurations"
cat > "$destination/pubspec.yaml" <<'EOF'
name: smt_mobile
description: Generated by fake Flutter CLI.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.9"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
EOF
printf 'include: package:flutter_lints/flutter.yaml\n' > "$destination/analysis_options.yaml"
printf 'created by Flutter CLI\n' > "$destination/lib/main.dart"
printf 'created by Flutter CLI\n' > "$destination/test/widget_test.dart"
printf 'created by Flutter CLI\n' > "$destination/integration_test/app_test.dart"
printf 'lock generated by Flutter CLI\n' > "$destination/pubspec.lock"
printf 'include: cli-analysis.yaml\n' > "$destination/analysis_options.yaml"
printf 'created by Flutter CLI\n' > "$destination/android/cli-owned.txt"
printf 'created by Flutter CLI\n' > "$destination/ios/cli-owned.txt"
printf 'workspace\n' > "$destination/.idea/workspace.xml"
printf 'modules\n' > "$destination/.idea/modules.xml"
printf 'library\n' > "$destination/.idea/libraries/flutter.xml"
printf 'run configuration\n' > "$destination/.idea/runConfigurations/flutter.xml"
`
	if err := os.WriteFile(filepath.Join(directory, "asdf"), []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", directory+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("SMT_FAKE_ASDF_LOG", logPath)
	if fail {
		t.Setenv("SMT_FAKE_ASDF_FAIL", "1")
	} else {
		t.Setenv("SMT_FAKE_ASDF_FAIL", "0")
	}
	return logPath
}

func readFakeASDFInvocation(t *testing.T, logPath string) (string, []string, string) {
	t.Helper()
	contents, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatal(err)
	}
	var cwd, versions string
	var args []string
	for _, line := range strings.Split(strings.TrimSpace(string(contents)), "\n") {
		switch {
		case strings.HasPrefix(line, "cwd="):
			cwd = strings.TrimPrefix(line, "cwd=")
		case strings.HasPrefix(line, "tool-versions="):
			versions = strings.TrimPrefix(line, "tool-versions=")
		case strings.HasPrefix(line, "arg="):
			args = append(args, strings.TrimPrefix(line, "arg="))
		}
	}
	return cwd, args, versions
}
