// Package runtime defines the deterministic, offline contract for the local
// OCI runtime artifacts. It does not execute Podman, Compose, or health checks.
package runtime

import (
	"fmt"
	"hash/fnv"
	"path/filepath"
	"strings"
)

const (
	ServiceWeb      = "web"
	ServiceAPI      = "api"
	ServiceDatabase = "database"
	ServiceIdentity = "zitadel"

	defaultWebPort           = 3000
	defaultAPIPort           = 8080
	defaultDatabasePort      = 5432
	defaultIdentityPort      = 8081
	defaultDatabasePassword  = "smt-dev-password"
	defaultIdentityPassword  = "smt-zitadel-password"
	defaultIdentityMasterkey = "smt-zitadel-masterkey-local-0000"
	defaultIdentityHumanUser = "zitadel-admin"
	defaultIdentityHumanPass = "Smt-Zitadel-Local-2026!"
	defaultIdentityPATExpiry = "2099-12-31T23:59:59Z"
	defaultZitadelVersion    = "v4.16.2"
)

// Selection identifies the OCI services included in a generated workspace.
// Mobile is intentionally absent because it is not an OCI service.
type Selection struct {
	Web      bool
	API      bool
	Database bool
	Identity bool
}

// ServiceIDs returns selected services in their canonical Compose order.
func (s Selection) ServiceIDs() []string {
	var services []string
	if s.Web {
		services = append(services, ServiceWeb)
	}
	if s.API {
		services = append(services, ServiceAPI)
	}
	if s.Database {
		services = append(services, ServiceDatabase)
	}
	if s.Identity {
		services = append(services, ServiceIdentity)
	}
	return services
}

// PortOverrides contains optional host-port overrides. Zero means use the
// reviewed default; every non-zero value must be a TCP port in range.
type PortOverrides struct {
	Web      int
	API      int
	Database int
	Identity int
}

// Ports is an alias retained as a concise name for callers that already have
// resolved or override port values.
type Ports = PortOverrides

// RenderOptions controls pure runtime artifact rendering.
type RenderOptions struct {
	WorkspacePath string
	Selection     Selection
	Ports         PortOverrides
}

// Artifacts contains the runtime files generated by this package.
type Artifacts struct {
	Compose        []byte
	EnvExample     []byte
	TraefikDynamic []byte
}

// NormalizeProjectName derives a safe Compose project name from a workspace
// destination basename. It never includes parent path, machine, user, or
// time-dependent data.
func NormalizeProjectName(workspacePath string) string {
	base := filepath.Base(filepath.Clean(workspacePath))
	if workspacePath == "" || base == "." || base == string(filepath.Separator) {
		return "smt-workspace"
	}
	base = strings.ToLower(base)
	var b strings.Builder
	separator := false
	for _, r := range base {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			separator = false
			continue
		}
		if !separator {
			b.WriteByte('-')
			separator = true
		}
	}
	name := strings.Trim(b.String(), "-")
	if len(name) > 63 {
		name = strings.TrimRight(name[:63], "-")
	}
	if name == "" {
		return "smt-workspace"
	}
	return name
}

// Render returns deterministic Compose and environment-example artifacts.
func Render(options RenderOptions) (Artifacts, error) {
	if err := validateSelection(options.Selection); err != nil {
		return Artifacts{}, err
	}
	ports, err := resolvePorts(options.Ports)
	if err != nil {
		return Artifacts{}, err
	}
	project := NormalizeProjectName(options.WorkspacePath)
	examplePorts := workspacePorts(project, ports, options.Ports)
	return Artifacts{
		Compose:        []byte(renderCompose(project, options.Selection, ports)),
		EnvExample:     []byte(renderEnvExample(project, examplePorts, options.Selection.Identity)),
		TraefikDynamic: []byte(renderTraefikDynamic(options.Selection.Identity)),
	}, nil
}

// RenderCompose renders only compose.yaml for callers that do not need the
// environment example.
func RenderCompose(options RenderOptions) ([]byte, error) {
	artifacts, err := Render(options)
	if err != nil {
		return nil, err
	}
	return artifacts.Compose, nil
}

// RenderEnvExample renders only .env.example for callers that do not need
// Compose output.
func RenderEnvExample(options RenderOptions) ([]byte, error) {
	artifacts, err := Render(options)
	if err != nil {
		return nil, err
	}
	return artifacts.EnvExample, nil
}

type resolvedPorts struct {
	web, api, database, identity int
}

func resolvePorts(overrides PortOverrides) (resolvedPorts, error) {
	if overrides.Web < 0 || overrides.Web > 65535 {
		return resolvedPorts{}, invalidPort("WEB_PORT", overrides.Web)
	}
	if overrides.API < 0 || overrides.API > 65535 {
		return resolvedPorts{}, invalidPort("API_PORT", overrides.API)
	}
	if overrides.Database < 0 || overrides.Database > 65535 {
		return resolvedPorts{}, invalidPort("DATABASE_PORT", overrides.Database)
	}
	if overrides.Identity < 0 || overrides.Identity > 65535 {
		return resolvedPorts{}, invalidPort("ZITADEL_PORT", overrides.Identity)
	}
	ports := resolvedPorts{web: defaultWebPort, api: defaultAPIPort, database: defaultDatabasePort, identity: defaultIdentityPort}
	if overrides.Web != 0 {
		ports.web = overrides.Web
	}
	if overrides.API != 0 {
		ports.api = overrides.API
	}
	if overrides.Database != 0 {
		ports.database = overrides.Database
	}
	if overrides.Identity != 0 {
		ports.identity = overrides.Identity
	}
	return ports, nil
}

func invalidPort(key string, port int) error {
	return fmt.Errorf("%s must be a decimal TCP port from 1 through 65535 (got %d); change %s", key, port, key)
}

func workspacePorts(project string, ports resolvedPorts, overrides PortOverrides) resolvedPorts {
	offset := projectPortOffset(project)
	if overrides.Web == 0 {
		ports.web = defaultWebPort + offset
	}
	if overrides.API == 0 {
		ports.api = defaultAPIPort + offset
	}
	if overrides.Database == 0 {
		ports.database = defaultDatabasePort + offset
	}
	if overrides.Identity == 0 {
		ports.identity = defaultIdentityPort + offset
	}
	return ports
}

func projectPortOffset(project string) int {
	hash := fnv.New32a()
	_, _ = hash.Write([]byte(project))
	return int(hash.Sum32() % 1000)
}

func validateSelection(selection Selection) error {
	if selection.Identity && !selection.Database {
		return fmt.Errorf("identity selection requires database selection")
	}
	return nil
}

func renderCompose(project string, selection Selection, ports resolvedPorts) string {
	var b strings.Builder
	fmt.Fprintf(&b, "name: %s\n", project)
	if len(selection.ServiceIDs()) == 0 {
		b.WriteString("services: {}\n")
		return b.String()
	}
	b.WriteString("services:\n")
	if selection.Web {
		b.WriteString("  web:\n")
		b.WriteString("    build:\n      context: ./web-app\n      dockerfile: Containerfile\n")
		fmt.Fprintf(&b, "    ports:\n      - \"${WEB_PORT:-%d}:3000\"\n", ports.web)
		if selection.API {
			b.WriteString("    environment:\n      API_BASE_URL: \"${API_BASE_URL:-http://api:8080}\"\n")
		}
		b.WriteString("    healthcheck:\n      test: [\"CMD-SHELL\", \"wget -qO- http://localhost:3000/healthz >/dev/null\"]\n      interval: 5s\n      timeout: 5s\n      retries: 10\n")
		if selection.API {
			b.WriteString("    depends_on:\n      api:\n        condition: service_healthy\n")
		}
	}
	if selection.API {
		b.WriteString("  api:\n")
		b.WriteString("    build:\n      context: ./apis\n      dockerfile: Containerfile\n      args:\n        TARGETOS: \"${SMT_API_TARGETOS:-linux}\"\n        TARGETARCH: \"${SMT_API_TARGETARCH:-}\"\n")
		fmt.Fprintf(&b, "    ports:\n      - \"${API_PORT:-%d}:8080\"\n", ports.api)
		if selection.Database || selection.Identity {
			b.WriteString("    environment:\n")
			if selection.Database {
				b.WriteString("      DATABASE_HOST: database\n      DATABASE_PORT: \"5432\"\n      DATABASE_NAME: smt\n      DATABASE_USER: smt\n      DATABASE_PASSWORD: \"${DATABASE_PASSWORD:-}\"\n")
			}
			if selection.Identity {
				b.WriteString("      OIDC_ISSUER_URL: \"${OIDC_ISSUER_URL:-}\"\n      OIDC_DISCOVERY_URL: \"${OIDC_DISCOVERY_URL:-}\"\n      OIDC_JWKS_URL: \"${OIDC_JWKS_URL:-}\"\n      OIDC_AUDIENCE: \"${OIDC_AUDIENCE:-}\"\n      OIDC_REQUIRED_SCOPES: \"${OIDC_REQUIRED_SCOPES:-openid,profile,email}\"\n")
			}
		}
		b.WriteString("    healthcheck:\n      test: [\"CMD-SHELL\", \"wget -qO- http://localhost:8080/healthz >/dev/null && wget -qO- http://localhost:8080/readyz >/dev/null\"]\n      interval: 5s\n      timeout: 5s\n      retries: 10\n")
		if selection.Database {
			b.WriteString("    depends_on:\n      database:\n        condition: service_healthy\n")
		}
		if selection.Identity {
			b.WriteString("    networks: [default, zitadel]\n")
		}
	}
	if selection.Database {
		b.WriteString("  database:\n")
		b.WriteString("    build:\n      context: ./database\n      dockerfile: Containerfile\n")
		fmt.Fprintf(&b, "    ports:\n      - \"${DATABASE_PORT:-%d}:5432\"\n", ports.database)
		b.WriteString("    environment:\n      POSTGRES_DB: smt\n      POSTGRES_USER: smt\n      POSTGRES_PASSWORD: \"${DATABASE_PASSWORD:-}\"\n")
		b.WriteString("    volumes:\n      - database-data:/var/lib/postgresql\n")
		b.WriteString("    healthcheck:\n      test: [\"CMD-SHELL\", \"pg_isready -h database -U smt -d smt\"]\n      interval: 5s\n      timeout: 5s\n      retries: 10\n")
		if selection.Identity {
			b.WriteString("    networks: [default, zitadel]\n")
		}
	}
	if selection.Identity {
		b.WriteString("  zitadel-db-init:\n")
		b.WriteString("    image: \"${ZITADEL_DB_INIT_IMAGE:-postgres:18-alpine}\"\n")
		b.WriteString("    restart: \"no\"\n")
		b.WriteString("    depends_on:\n      database:\n        condition: service_healthy\n")
		b.WriteString("    environment:\n      PGHOST: database\n      PGPORT: \"5432\"\n      PGPASSWORD: \"${DATABASE_PASSWORD:-}\"\n      POSTGRES_USER: smt\n      POSTGRES_DB: smt\n      ZITADEL_DB_NAME: \"${ZITADEL_DB_NAME:-zitadel}\"\n      ZITADEL_DB_USER: \"${ZITADEL_DB_USER:-zitadel}\"\n      ZITADEL_DB_PASSWORD: \"${ZITADEL_DB_PASSWORD:-" + defaultIdentityPassword + "}\"\n")
		b.WriteString("    command:\n      - /bin/sh\n      - -c\n      - |\n        set -eu\n        psql --set=ON_ERROR_STOP=1 --username=\"$$POSTGRES_USER\" --dbname=\"$$POSTGRES_DB\" --set=zitadel_user=\"$$ZITADEL_DB_USER\" --set=zitadel_password=\"$$ZITADEL_DB_PASSWORD\" <<'SQL'\n        SELECT format('CREATE ROLE %I LOGIN PASSWORD %L', :'zitadel_user', :'zitadel_password') WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'zitadel_user') \\gexec\n        SQL\n        psql --set=ON_ERROR_STOP=1 --username=\"$$POSTGRES_USER\" --dbname=\"$$POSTGRES_DB\" --set=zitadel_db=\"$$ZITADEL_DB_NAME\" --set=zitadel_user=\"$$ZITADEL_DB_USER\" <<'SQL'\n        SELECT format('CREATE DATABASE %I OWNER %I', :'zitadel_db', :'zitadel_user') WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = :'zitadel_db') \\gexec\n        SQL\n")
		b.WriteString("  zitadel:\n")
		b.WriteString("    image: \"${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:" + defaultZitadelVersion + "}\"\n")
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("    command: [\"start-from-init\", \"--masterkey\", \"${ZITADEL_MASTERKEY:-" + defaultIdentityMasterkey + "}\"]\n")
		b.WriteString("    environment:\n      ZITADEL_PORT: \"8080\"\n      ZITADEL_EXTERNALDOMAIN: \"${ZITADEL_DOMAIN:-localhost}\"\n      ZITADEL_EXTERNALPORT: \"${ZITADEL_EXTERNALPORT:-" + fmt.Sprintf("%d", ports.identity) + "}\"\n      ZITADEL_EXTERNALSECURE: \"${ZITADEL_EXTERNALSECURE:-false}\"\n      ZITADEL_TLS_ENABLED: \"false\"\n      ZITADEL_DATABASE_POSTGRES_DSN: \"${ZITADEL_DATABASE_POSTGRES_DSN:-postgresql://zitadel:" + defaultIdentityPassword + "@database:5432/zitadel?sslmode=disable}\"\n      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: \"false\"\n      ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH: /zitadel/bootstrap/login-client.pat\n      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME: login-client\n      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME: Automatically Initialized IAM_LOGIN_CLIENT\n      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: \"true\"\n      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI: \"${ZITADEL_PUBLIC_SCHEME:-http}://${ZITADEL_DOMAIN:-localhost}:${ZITADEL_EXTERNALPORT:-" + fmt.Sprintf("%d", ports.identity) + "}/ui/v2/login/\"\n      ZITADEL_OIDC_DEFAULTLOGINURLV2: \"${ZITADEL_PUBLIC_SCHEME:-http}://${ZITADEL_DOMAIN:-localhost}:${ZITADEL_EXTERNALPORT:-" + fmt.Sprintf("%d", ports.identity) + "}/ui/v2/login/login?authRequest=\"\n      ZITADEL_OIDC_DEFAULTLOGOUTURLV2: \"${ZITADEL_PUBLIC_SCHEME:-http}://${ZITADEL_DOMAIN:-localhost}:${ZITADEL_EXTERNALPORT:-" + fmt.Sprintf("%d", ports.identity) + "}/ui/v2/login/logout?post_logout_redirect=\"\n      ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED: \"${ZITADEL_ACCESS_LOG_STDOUT_ENABLED:-true}\"\n")
		b.WriteString("    volumes:\n      - zitadel-bootstrap:/zitadel/bootstrap\n")
		b.WriteString("    networks: [zitadel]\n")
		b.WriteString("    depends_on:\n      database:\n        condition: service_healthy\n      zitadel-db-init:\n        condition: service_completed_successfully\n")
		b.WriteString("    healthcheck:\n      test: [\"CMD\", \"/app/zitadel\", \"ready\"]\n      interval: 10s\n      timeout: 30s\n      retries: 12\n      start_period: 20s\n")
		b.WriteString("  zitadel-login:\n    image: \"${ZITADEL_LOGIN_IMAGE:-ghcr.io/zitadel/zitadel-login:" + defaultZitadelVersion + "}\"\n    restart: unless-stopped\n    environment:\n      ZITADEL_API_URL: http://zitadel:8080\n      NEXT_PUBLIC_BASE_PATH: /ui/v2/login\n      ZITADEL_SERVICE_USER_TOKEN_FILE: /zitadel/bootstrap/login-client.pat\n      CUSTOM_REQUEST_HEADERS: \"Host:${ZITADEL_DOMAIN:-localhost},X-Forwarded-Proto:${ZITADEL_PUBLIC_SCHEME:-http}\"\n    volumes:\n      - zitadel-bootstrap:/zitadel/bootstrap:ro\n    networks: [zitadel]\n    depends_on:\n      zitadel:\n        condition: service_healthy\n    healthcheck:\n      test: [\"CMD\", \"/bin/sh\", \"-c\", \"node /app/healthcheck.mjs http://localhost:3000/ui/v2/login/healthy\"]\n      interval: 10s\n      timeout: 30s\n      retries: 12\n      start_period: 20s\n")
		b.WriteString("  proxy:\n")
		b.WriteString("    image: \"${TRAEFIK_IMAGE:-traefik:v3.5.3}\"\n")
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("    command:\n      - --providers.file.directory=/etc/traefik/dynamic\n      - --providers.file.watch=true\n      - --entrypoints.web.address=:80\n      - --ping=true\n")
		b.WriteString("    ports:\n      - \"${ZITADEL_PORT:-" + fmt.Sprintf("%d", ports.identity) + "}:80\"\n")
		b.WriteString("    environment:\n      ZITADEL_DOMAIN: \"${ZITADEL_DOMAIN:-localhost}\"\n")
		b.WriteString("    networks: [zitadel]\n")
		b.WriteString("    volumes:\n      - ./traefik:/etc/traefik/dynamic:ro\n")
		b.WriteString("    depends_on:\n      zitadel:\n        condition: service_healthy\n      zitadel-login:\n        condition: service_healthy\n")
		fmt.Fprintf(&b, "networks:\n  zitadel:\n    name: \"${ZITADEL_NETWORK:-%s-zitadel}\"\n", project)
		fmt.Fprintf(&b, "\nvolumes:\n  database-data:\n    name: \"${DATABASE_VOLUME:-%s-postgres-data}\"\n  zitadel-bootstrap:\n    name: \"${ZITADEL_BOOTSTRAP_VOLUME:-%s-zitadel-bootstrap}\"\n", project, project)
		compose := b.String()
		compose = strings.ReplaceAll(compose, `ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: "false"`, `ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: "${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED:-false}"`)
		compose = strings.ReplaceAll(compose, "      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: \"${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED:-false}\"\n", "      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: \"${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED:-false}\"\n      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: \"${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME:-"+defaultIdentityHumanUser+"}\"\n      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: \"${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD:-}\"\n      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE: \"${ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE:-}\"\n")
		return compose
	}
	if selection.Database {
		fmt.Fprintf(&b, "\nvolumes:\n  database-data:\n    name: \"${DATABASE_VOLUME:-%s-postgres-data}\"\n", project)
	}
	return b.String()
}

func renderTraefikDynamic(identitySelected bool) string {
	if !identitySelected {
		return ""
	}
	return "http:\n" +
		"  routers:\n" +
		"    zitadel-api:\n" +
		"      rule: 'Host(`{{ env \"ZITADEL_DOMAIN\" }}`) && !PathPrefix(`/ui/v2/login`)'\n" +
		"      entryPoints:\n" +
		"        - web\n" +
		"      service: zitadel-api\n" +
		"    zitadel-login:\n" +
		"      rule: 'Host(`{{ env \"ZITADEL_DOMAIN\" }}`) && PathPrefix(`/ui/v2/login`)'\n" +
		"      entryPoints:\n" +
		"        - web\n" +
		"      service: zitadel-login\n" +
		"  services:\n" +
		"    zitadel-api:\n" +
		"      loadBalancer:\n" +
		"        servers:\n" +
		"          - url: h2c://zitadel:8080\n" +
		"    zitadel-login:\n" +
		"      loadBalancer:\n" +
		"        servers:\n" +
		"          - url: http://zitadel-login:3000\n"
}

func renderEnvExample(project string, ports resolvedPorts, identitySelected bool) string {
	env := fmt.Sprintf("COMPOSE_PROJECT_NAME=%s\nWEB_PORT=%d\nAPI_PORT=%d\nDATABASE_PORT=%d\nDATABASE_VOLUME=%s-postgres-data\nAPI_BASE_URL=http://api:8080\nSMT_API_TARGETOS=linux\nSMT_API_TARGETARCH=\nDATABASE_HOST=database\nDATABASE_NAME=smt\nDATABASE_USER=smt\nDATABASE_PASSWORD=%s\n", project, ports.web, ports.api, ports.database, project, defaultDatabasePassword)
	if identitySelected {
		env += "# Production deployments must replace the pinned tags below with immutable @sha256 image references.\n"
		env += fmt.Sprintf("ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME=%s\nZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=%s\nZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED=false\nZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE=%s\n", defaultIdentityHumanUser, defaultIdentityHumanPass, defaultIdentityPATExpiry)
		env += fmt.Sprintf("ZITADEL_PORT=%d\nZITADEL_NETWORK=%s-zitadel\nZITADEL_BOOTSTRAP_VOLUME=%s-zitadel-bootstrap\nZITADEL_VERSION=%s\nZITADEL_IMAGE=ghcr.io/zitadel/zitadel:%s\nZITADEL_LOGIN_IMAGE=ghcr.io/zitadel/zitadel-login:%s\nTRAEFIK_IMAGE=traefik:v3.5.3\nZITADEL_DB_INIT_IMAGE=postgres:18-alpine\nZITADEL_DB_NAME=zitadel\nZITADEL_DB_USER=zitadel\nZITADEL_DB_PASSWORD=%s\nZITADEL_DATABASE_POSTGRES_DSN=postgresql://zitadel:%s@database:5432/zitadel?sslmode=disable\nZITADEL_MASTERKEY=%s\nZITADEL_DOMAIN=localhost\nZITADEL_EXTERNALPORT=%d\nZITADEL_EXTERNALSECURE=false\nZITADEL_PUBLIC_SCHEME=http\nZITADEL_HEALTH_PATH=/debug/healthz\nZITADEL_READY_PATH=/debug/ready\nOIDC_ISSUER_URL=http://localhost:%d\nOIDC_DISCOVERY_URL=http://localhost:%d/.well-known/openid-configuration\nOIDC_JWKS_URL=http://localhost:%d/oauth/v2/keys\nOIDC_AUDIENCE=smt-api\nOIDC_REQUIRED_SCOPES=openid,profile,email\nOIDC_CLIENT_ID=local-placeholder\nOIDC_WEB_REDIRECT_URI=http://localhost:%d/auth/callback\nOIDC_MOBILE_REDIRECT_URI=com.example.smt:/oauth/callback\n", ports.identity, project, project, defaultZitadelVersion, defaultZitadelVersion, defaultZitadelVersion, defaultIdentityPassword, defaultIdentityPassword, defaultIdentityMasterkey, ports.identity, ports.identity, ports.identity, ports.identity, ports.web)
	}
	return env
}

// PreflightOptions provides injectable checks for future Taskfile/CLI use.
// Apply intentionally does not call Preflight.
type PreflightOptions struct {
	Selection    Selection
	Ports        PortOverrides
	CheckPort    func(service string, port int) error
	CheckPodman  func() error
	CheckCompose func() error
}

// Preflight validates selected host ports and optional Podman prerequisites
// without executing any external command itself.
func Preflight(options PreflightOptions) error {
	if len(options.Selection.ServiceIDs()) == 0 {
		return nil
	}
	ports, err := resolvePorts(options.Ports)
	if err != nil {
		return err
	}
	bindings := selectedPorts(options.Selection, ports)
	for i, left := range bindings {
		for _, right := range bindings[i+1:] {
			if left.port == right.port {
				return fmt.Errorf("%s host port %d conflicts with %s; change %s or %s", left.service, left.port, right.service, left.key, right.key)
			}
		}
	}
	if options.CheckPort != nil {
		for _, binding := range bindings {
			if err := options.CheckPort(binding.service, binding.port); err != nil {
				return fmt.Errorf("%s host port %d is unavailable: %v; change %s", binding.service, binding.port, err, binding.key)
			}
		}
	}
	if options.CheckPodman != nil {
		if err := options.CheckPodman(); err != nil {
			return fmt.Errorf("Podman prerequisite is unavailable: %v; install Podman", err)
		}
	}
	if options.CheckCompose != nil {
		if err := options.CheckCompose(); err != nil {
			return fmt.Errorf("Podman Compose prerequisite is unavailable: %v; install or configure Podman Compose", err)
		}
	}
	return nil
}

type portBinding struct {
	service string
	key     string
	port    int
}

func selectedPorts(selection Selection, ports resolvedPorts) []portBinding {
	var bindings []portBinding
	if selection.Web {
		bindings = append(bindings, portBinding{service: ServiceWeb, key: "WEB_PORT", port: ports.web})
	}
	if selection.API {
		bindings = append(bindings, portBinding{service: ServiceAPI, key: "API_PORT", port: ports.api})
	}
	if selection.Database {
		bindings = append(bindings, portBinding{service: ServiceDatabase, key: "DATABASE_PORT", port: ports.database})
	}
	if selection.Identity {
		bindings = append(bindings, portBinding{service: ServiceIdentity, key: "ZITADEL_PORT", port: ports.identity})
	}
	return bindings
}
