// Package runtime defines the deterministic, offline contract for the local
// OCI runtime artifacts. It does not execute Podman, Compose, or health checks.
package runtime

import (
	"fmt"
	"path/filepath"
	"strings"
)

const (
	ServiceWeb      = "web"
	ServiceAPI      = "api"
	ServiceDatabase = "database"

	defaultWebPort      = 3000
	defaultAPIPort      = 8080
	defaultDatabasePort = 5432
)

// Selection identifies the OCI services included in a generated workspace.
// Mobile is intentionally absent because it is not an OCI service.
type Selection struct {
	Web      bool
	API      bool
	Database bool
}

// ServiceIDs returns selected services in their canonical Compose order.
func (s Selection) ServiceIDs() []string {
	var services []string
	if s.Web {
		services = append(services, ServiceWeb)
	}
	if s.API {
		services = append(services, ServiceAPI)
	}
	if s.Database {
		services = append(services, ServiceDatabase)
	}
	return services
}

// PortOverrides contains optional host-port overrides. Zero means use the
// reviewed default; every non-zero value must be a TCP port in range.
type PortOverrides struct {
	Web      int
	API      int
	Database int
}

// Ports is an alias retained as a concise name for callers that already have
// resolved or override port values.
type Ports = PortOverrides

// RenderOptions controls pure runtime artifact rendering.
type RenderOptions struct {
	WorkspacePath string
	Selection     Selection
	Ports         PortOverrides
}

// Artifacts contains the only runtime files generated by this package.
type Artifacts struct {
	Compose    []byte
	EnvExample []byte
}

// NormalizeProjectName derives a safe Compose project name from a workspace
// destination basename. It never includes parent path, machine, user, or
// time-dependent data.
func NormalizeProjectName(workspacePath string) string {
	base := filepath.Base(filepath.Clean(workspacePath))
	if workspacePath == "" || base == "." || base == string(filepath.Separator) {
		return "smt-workspace"
	}
	base = strings.ToLower(base)
	var b strings.Builder
	separator := false
	for _, r := range base {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			separator = false
			continue
		}
		if !separator {
			b.WriteByte('-')
			separator = true
		}
	}
	name := strings.Trim(b.String(), "-")
	if len(name) > 63 {
		name = strings.TrimRight(name[:63], "-")
	}
	if name == "" {
		return "smt-workspace"
	}
	return name
}

// Render returns deterministic Compose and environment-example artifacts.
func Render(options RenderOptions) (Artifacts, error) {
	ports, err := resolvePorts(options.Ports)
	if err != nil {
		return Artifacts{}, err
	}
	project := NormalizeProjectName(options.WorkspacePath)
	return Artifacts{
		Compose:    []byte(renderCompose(project, options.Selection, ports)),
		EnvExample: []byte(renderEnvExample(project, ports)),
	}, nil
}

// RenderCompose renders only compose.yaml for callers that do not need the
// environment example.
func RenderCompose(options RenderOptions) ([]byte, error) {
	artifacts, err := Render(options)
	if err != nil {
		return nil, err
	}
	return artifacts.Compose, nil
}

// RenderEnvExample renders only .env.example for callers that do not need
// Compose output.
func RenderEnvExample(options RenderOptions) ([]byte, error) {
	artifacts, err := Render(options)
	if err != nil {
		return nil, err
	}
	return artifacts.EnvExample, nil
}

type resolvedPorts struct {
	web, api, database int
}

func resolvePorts(overrides PortOverrides) (resolvedPorts, error) {
	if overrides.Web < 0 || overrides.Web > 65535 {
		return resolvedPorts{}, invalidPort("WEB_PORT", overrides.Web)
	}
	if overrides.API < 0 || overrides.API > 65535 {
		return resolvedPorts{}, invalidPort("API_PORT", overrides.API)
	}
	if overrides.Database < 0 || overrides.Database > 65535 {
		return resolvedPorts{}, invalidPort("DATABASE_PORT", overrides.Database)
	}
	ports := resolvedPorts{web: defaultWebPort, api: defaultAPIPort, database: defaultDatabasePort}
	if overrides.Web != 0 {
		ports.web = overrides.Web
	}
	if overrides.API != 0 {
		ports.api = overrides.API
	}
	if overrides.Database != 0 {
		ports.database = overrides.Database
	}
	return ports, nil
}

func invalidPort(key string, port int) error {
	return fmt.Errorf("%s must be a decimal TCP port from 1 through 65535 (got %d); change %s", key, port, key)
}

func renderCompose(project string, selection Selection, ports resolvedPorts) string {
	var b strings.Builder
	fmt.Fprintf(&b, "name: %s\n", project)
	if len(selection.ServiceIDs()) == 0 {
		b.WriteString("services: {}\n")
		return b.String()
	}
	b.WriteString("services:\n")
	if selection.Web {
		b.WriteString("  web:\n")
		b.WriteString("    build:\n      context: ./web-app\n")
		fmt.Fprintf(&b, "    ports:\n      - \"${WEB_PORT:-%d}:3000\"\n", ports.web)
		if selection.API {
			b.WriteString("    environment:\n      API_BASE_URL: \"${API_BASE_URL:-http://api:8080}\"\n")
		}
		b.WriteString("    healthcheck:\n      test: [\"CMD-SHELL\", \"wget -qO- http://localhost:3000/healthz >/dev/null\"]\n      interval: 5s\n      timeout: 5s\n      retries: 10\n")
		if selection.API {
			b.WriteString("    depends_on:\n      api:\n        condition: service_healthy\n")
		}
	}
	if selection.API {
		b.WriteString("  api:\n")
		b.WriteString("    build:\n      context: ./apis\n")
		fmt.Fprintf(&b, "    ports:\n      - \"${API_PORT:-%d}:8080\"\n", ports.api)
		if selection.Database {
			b.WriteString("    environment:\n      DATABASE_HOST: database\n      DATABASE_PORT: \"5432\"\n      DATABASE_NAME: smt\n      DATABASE_USER: smt\n      DATABASE_PASSWORD: \"${DATABASE_PASSWORD:-}\"\n")
		}
		b.WriteString("    healthcheck:\n      test: [\"CMD-SHELL\", \"wget -qO- http://localhost:8080/healthz >/dev/null && wget -qO- http://localhost:8080/readyz >/dev/null\"]\n      interval: 5s\n      timeout: 5s\n      retries: 10\n")
		if selection.Database {
			b.WriteString("    depends_on:\n      database:\n        condition: service_healthy\n")
		}
	}
	if selection.Database {
		b.WriteString("  database:\n")
		b.WriteString("    build:\n      context: ./database\n")
		fmt.Fprintf(&b, "    ports:\n      - \"${DATABASE_PORT:-%d}:5432\"\n", ports.database)
		b.WriteString("    environment:\n      POSTGRES_DB: smt\n      POSTGRES_USER: smt\n      POSTGRES_PASSWORD: \"${DATABASE_PASSWORD:-}\"\n")
		b.WriteString("    healthcheck:\n      test: [\"CMD-SHELL\", \"pg_isready -h database -U smt -d smt\"]\n      interval: 5s\n      timeout: 5s\n      retries: 10\n")
	}
	return b.String()
}

func renderEnvExample(project string, ports resolvedPorts) string {
	return fmt.Sprintf("COMPOSE_PROJECT_NAME=%s\nWEB_PORT=%d\nAPI_PORT=%d\nDATABASE_PORT=%d\nAPI_BASE_URL=http://api:8080\nDATABASE_HOST=database\nDATABASE_NAME=smt\nDATABASE_USER=smt\nDATABASE_PASSWORD=\n", project, ports.web, ports.api, ports.database)
}

// PreflightOptions provides injectable checks for future Taskfile/CLI use.
// Apply intentionally does not call Preflight.
type PreflightOptions struct {
	Selection    Selection
	Ports        PortOverrides
	CheckPort    func(service string, port int) error
	CheckPodman  func() error
	CheckCompose func() error
}

// Preflight validates selected host ports and optional Podman prerequisites
// without executing any external command itself.
func Preflight(options PreflightOptions) error {
	if len(options.Selection.ServiceIDs()) == 0 {
		return nil
	}
	ports, err := resolvePorts(options.Ports)
	if err != nil {
		return err
	}
	bindings := selectedPorts(options.Selection, ports)
	for i, left := range bindings {
		for _, right := range bindings[i+1:] {
			if left.port == right.port {
				return fmt.Errorf("%s host port %d conflicts with %s; change %s or %s", left.service, left.port, right.service, left.key, right.key)
			}
		}
	}
	if options.CheckPort != nil {
		for _, binding := range bindings {
			if err := options.CheckPort(binding.service, binding.port); err != nil {
				return fmt.Errorf("%s host port %d is unavailable: %v; change %s", binding.service, binding.port, err, binding.key)
			}
		}
	}
	if options.CheckPodman != nil {
		if err := options.CheckPodman(); err != nil {
			return fmt.Errorf("Podman prerequisite is unavailable: %v; install Podman", err)
		}
	}
	if options.CheckCompose != nil {
		if err := options.CheckCompose(); err != nil {
			return fmt.Errorf("Podman Compose prerequisite is unavailable: %v; install or configure Podman Compose", err)
		}
	}
	return nil
}

type portBinding struct {
	service string
	key     string
	port    int
}

func selectedPorts(selection Selection, ports resolvedPorts) []portBinding {
	var bindings []portBinding
	if selection.Web {
		bindings = append(bindings, portBinding{service: ServiceWeb, key: "WEB_PORT", port: ports.web})
	}
	if selection.API {
		bindings = append(bindings, portBinding{service: ServiceAPI, key: "API_PORT", port: ports.api})
	}
	if selection.Database {
		bindings = append(bindings, portBinding{service: ServiceDatabase, key: "DATABASE_PORT", port: ports.database})
	}
	return bindings
}
